CREATE TABLE PAIS (COD_PAIS NUMBER PRIMARY KEY,
                NOME  VARCHAR2(30));

CREATE TABLE ESTADO (COD_ESTADO NUMBER PRIMARY KEY,
                 NOME_ESTADO VARCHAR(30),
                 COD_PAIS NUMBER);
                 
ALTER TABLE ESTADO ADD CONSTRAINT
FK_ESTADO FOREIGN KEY (COD_PAIS) REFERENCES
PAIS(COD_PAIS);

CREATE TABLE BAIRRO (COD_BAIRRO NUMBER PRIMARY KEY,
                        NOME_BAIRRO VARCHAR2(30),
                        COD_CIDADE NUMBER);
ALTER TABLE BAIRRO ADD CONSTRAINT 
FK_BAIRRO FOREIGN KEY (COD_CIDADE) REFERENCES CIDADE (COD_CIDADE);